### ISSUE TITLE
Xcode 15: issues with run script to set branch name

### ISSUE THREAD

**Issue by bjornoleh** [Artificial-Pancreas/iAPS#155]
Discord reports:

1. https://discord.com/channels/1120154740857245808/1123067925746700379/1136625513755070495
2. https://discord.com/channels/1120154740857245808/1123067925746700379/1136897524821659668

These reports are possibly related, but needs more checking.

**Comment by bjornoleh** [comment]
Some background info:

The run script for retrieving branch name was taken from this post on Stack Overflow:

https://stackoverflow.com/questions/47795580/retrieve-branch-name-inside-ios-project

It was introduced with this commit:
https://github.com/Artificial-Pancreas/iAPS/commit/0ad0d84fe4e722ee321be15749e9edc95a40e42d

**Comment by scrappy** [comment]
This is fixed and tested in my latest PR:

https://github.com/Artificial-Pancreas/iAPS/pull/175

**Comment by bjornoleh** [comment]
I believe the root cause of this issue was fixed in the released version Xcode 15, closing the issue now.

**Comment by bjornoleh** [comment]
When attempting to do a browser build with GitHub actions using Xcode 15.0. it appears we run into the same issue as was previously present in Xcode 15 beta.

```
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/runner/Library/Developer/Xcode/DerivedData/FreeAPS-ffhbcjzbszlapbgzecdzvzprscam/Build/Intermediates.noindex/ArchiveIntermediates/FreeAPS\ X/IntermediateBuildFilesPath/FreeAPS.build/Release-iphoneos/FreeAPS.build/Script-B99D8B8E295F34DB00420AB8.sh (in target 'FreeAPS' from project 'FreeAPS')
(1 failure)
[10:21:36]: Exit status: 65
```

@scrappy , can you check if this is the same issue you encountered? If so, I suspect the fixes that went into the released version of Xcode 15 did not make it into the macos-13 runner image used in GitHub actions.

Info on currently available Xcode versions in macos-13:
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

macos-14 is not yet available

**Comment by scrappy** [comment]
Not sure of exact error, but I am still seeing this with latest Xcode on my desktop ... and it is still reasonably sporatic, but when i do see it, I just implement my original fix of moving the Run script up and setting it to modify the Info.plist within the source code directory ...

**Comment by bjornoleh** [comment]
Thanks. I tried with your changes, but still getting

`** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/runner/Library/Developer/Xcode/DerivedData/FreeAPS-ffhbcjzbszlapbgzecdzvzprscam/Build/Intermediates.noindex/ArchiveIntermediates/FreeAPS\ X/IntermediateBuildFilesPath/FreeAPS.build/Release-iphoneos/FreeAPS.build/Script-B99D8B8E295F34DB00420AB8.sh (in target 'FreeAPS' from project 'FreeAPS')
(1 failure)
[11:27:22]: Exit status: 65 `

**Comment by bjornoleh** [comment]
@scrappy, your proposed changes actually worked. I made a mistake when testing at first, so did not test the actual changes at first.

The only issue I see is that with this change from  

`info_plist=\"${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}\"`

to

`info_plist="${SRCROOT}/FreeAPS/Resources/Info.plist"`

is that the latter wants to edit the Info.plist in the project for every build, specifically it sets `BuildBranch` to the current branch name and commit ID. This is tracked by git, and can easily be committed. Perhaps that does not matter much though, but I wonder if we could avoid it?

e.g:
```
<key>BuildBranch</key>
	<string>calendar_xcode_15 4287bd2f</string>
```

x

**Comment by bjornoleh** [comment]
Possibly a related issue, as a note for later:
https://discord.com/channels/1120154740857245808/1123067925746700379/1161053276234584114

**Comment by bjornoleh** [comment]
> When attempting to do a browser build with GitHub actions using Xcode 15.0. it appears we run into the same issue as was previously present in Xcode 15 beta.
> 
> ```
> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> 	PhaseScriptExecution Run\ Script /Users/runner/Library/Developer/Xcode/DerivedData/FreeAPS-ffhbcjzbszlapbgzecdzvzprscam/Build/Intermediates.noindex/ArchiveIntermediates/FreeAPS\ X/IntermediateBuildFilesPath/FreeAPS.build/Release-iphoneos/FreeAPS.build/Script-B99D8B8E295F34DB00420AB8.sh (in target 'FreeAPS' from project 'FreeAPS')
> (1 failure)
> [10:21:36]: Exit status: 65
> ```
> 
> @scrappy , can you check if this is the same issue you encountered? If so, I suspect the fixes that went into the released version of Xcode 15 did not make it into the macos-13 runner image used in GitHub actions.
> 
> Info on currently available Xcode versions in macos-13: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
> 
> macos-14 is not yet available

I think the issue with Xcode 15 in GitHub actions is that the same error occurs, but you can only build once in the same build environment, so it is not possible to build a second time like with Xcode locally. We will probably have to start using Xcode 15 in GitHub actions at some point, and then some other solution will be needed.

**Comment by bjornoleh** [comment]
Ok, I have a fix for this. For some reason, it seems like the changes we made to Info.plist with the run scrip was not available to Xcode at build time.

The solution was to write the branch name and git reference to a branch.txt file that is added to the Xcode FreeAPS project. This file is not tracked by Git, so it does not cause uncommitted changes. The file is viweable in the Xcode browser, so one can easily see which file was built last.

The build was successful for both Xcode 14.3 and Xcode 15.0, on both the Mac locally, and on GitHub Actions.

I will make the PR when having checked that I get the Statistics upload of branch name working properly.

**Comment by Jon-b-m** [comment]
Every late evening/night

**Comment by bjornoleh** [comment]
Thanks, working now.

Also tested that zip download of code gives a successful build, although the repository will not be initialized in this case, and there is no branch name or commit history. The "Branch:" info in settings will be empty, but works otherwise. Perhaps we should make sure the recommended way of getting APS code is by using the LnL build script, use git clone commands, or "Open in Xcode", instead of download zip (I have not checked the docks in a while).

Xcode build log when building (successfully) from zip download:
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by Jon-b-m** [comment]
Fixed in dev
